# Generated by Django 3.2.4 on 2021-06-18 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workboard', '0003_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='list',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='list', to='workboard.list'),
            preserve_default=False,
        ),
    ]
