# Generated by Django 3.2.4 on 2021-06-18 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workboard', '0004_ticket_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='project',
        ),
    ]
