# Generated by Django 3.2.4 on 2021-06-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workboard', '0005_remove_ticket_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
